/**
 * One-time question generator. Run with: npm run generate:questions
 *
 * Derives the interview dimensions and weighted answer options from the PRD
 * using the strongest model available -- this runs offline, so latency is free
 * and quality compounds across every future session.
 *
 * Writes to lib/questions.generated.ts, NOT lib/questions.ts. Diff the two by
 * hand, take what is better, and re-check lib/baseline.ts afterwards: the
 * baseline references option ids, so a regeneration can silently invalidate it.
 */
import { writeFileSync } from "node:fs";
import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { z } from "zod";
import { PRD } from "../lib/prd";
import { MODELS } from "../lib/models";

const Schema = z.object({
  dimensions: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      spectrumLow: z.string(),
      spectrumHigh: z.string(),
      whyItMatters: z.string(),
      question: z.string(),
      options: z.array(
        z.object({ id: z.string(), label: z.string(), detail: z.string() }),
      ),
    }),
  ),
});

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ANTHROPIC_API_KEY is not set. Load your .env first.");
    process.exit(1);
  }

  const client = new Anthropic();
  console.log(`Generating with ${MODELS.questionGeneration}...`);

  const response = await client.messages.parse({
    model: MODELS.questionGeneration,
    max_tokens: 16000,
    thinking: { type: "adaptive" },
    system:
      "You design interview questions that expose hidden disagreement between a product manager and an engineer reading the same spec.\n\n" +
      "Produce EXACTLY 4 dimensions. For each, exactly 4 answer options ordered from most aggressive/most thorough (FIRST) to most conservative/most minimal (LAST).\n\n" +
      "Requirements:\n" +
      "- Each dimension targets an ambiguity the spec leaves open that engineering must resolve before building.\n" +
      "- The 4 options must lie on ONE coherent axis, so that being 2 apart is a bigger disagreement than being 1 apart.\n" +
      "- `spectrumLow` must describe where the FIRST option sits and `spectrumHigh` where the LAST option sits. Getting these backwards inverts the whole axis, so check them against your own option order before answering.\n" +
      "- Every option must be defensible. No strawmen; a reasonable person should be able to pick any of them.\n" +
      "- Options must be mutually exclusive and concrete about consequences, not vague preferences.\n" +
      "- `whyItMatters`: one sentence on the cost of leaving it unresolved.\n" +
      "- ids are lowercase kebab-case.\n" +
      "- `label` under 8 words. `detail` one sentence.",
    messages: [
      {
        role: "user",
        content: `Design the interview for this spec.\n\nTITLE: ${PRD.title}\n\n${PRD.body}`,
      },
    ],
    output_config: { effort: "high", format: zodOutputFormat(Schema) },
  });

  const result = response.parsed_output;
  if (!result) throw new Error("Model returned no parsable output.");

  const source = `/**
 * GENERATED by scripts/generate-questions.ts -- review before adopting.
 * Copy into lib/questions.ts only after re-checking lib/baseline.ts option ids.
 */
import type { Dimension } from "./types";

export const DIMENSIONS: Dimension[] = ${JSON.stringify(
    result.dimensions.map((d) => ({
      id: d.id,
      title: d.title,
      spectrum: { low: d.spectrumLow, high: d.spectrumHigh },
      whyItMatters: d.whyItMatters,
      question: d.question,
      options: d.options.map((o, i) => ({ ...o, weight: i })),
    })),
    null,
    2,
  )};
`;

  writeFileSync("lib/questions.generated.ts", source);

  for (const d of result.dimensions) {
    if (d.options.length !== 4) {
      console.warn(`  ! "${d.title}" has ${d.options.length} options, expected 4`);
    }
  }
  console.log(`\nWrote lib/questions.generated.ts (${result.dimensions.length} dimensions)`);
  for (const d of result.dimensions) {
    console.log(`\n  ${d.title}`);
    console.log(`    axis: ${d.spectrumLow}  ->  ${d.spectrumHigh}`);
    console.log(`    ${d.question}`);
    d.options.forEach((o, i) => console.log(`      ${i}. ${o.label}`));
    console.log(`    ^ check option 0 matches "${d.spectrumLow}"`);
  }
  console.log("\nNext: diff against lib/questions.ts, then re-check lib/baseline.ts.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
